(() => {
  const mapElement = document.querySelector('#mapCanvas'), locationDialog = document.querySelector('#locationDialog'), locationInput = document.querySelector('#locationInput');
  const defaultCenter = [30.512, 114.405];
  const leafletMap = L.map(mapElement, { zoomControl: true, attributionControl: true }).setView(defaultCenter, 14); window.hanpinMap = leafletMap;
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(leafletMap);
  const userMarker = L.circleMarker(defaultCenter, { radius: 8, color: '#fff', weight: 3, fillColor: '#3d7ef0', fillOpacity: 1 }).addTo(leafletMap).bindTooltip('你的当前位置');
  const rangeCircle = L.circle(defaultCenter, { radius: 5000, color: '#6f9e12', weight: 1, fillColor: '#b8e742', fillOpacity: .08 }).addTo(leafletMap);
  function updateLocation(position) { const point = [position.coords.latitude, position.coords.longitude]; userMarker.setLatLng(point); rangeCircle.setLatLng(point); leafletMap.flyTo(point, 14, { animate: true, duration: 1 }); locationInput.value = `当前位置（${point[0].toFixed(3)}, ${point[1].toFixed(3)}）`; locationInput.dispatchEvent(new Event('change', { bubbles: true })); locationDialog.close(); }
  function requestLocation() { if (!window.isSecureContext) { alert('定位需要通过 localhost 或 HTTPS 打开网站。请运行 start.ps1 后访问 http://localhost:8080。'); return; } if (!navigator.geolocation) { alert('此浏览器不支持定位，请手动填写位置。'); return; } navigator.geolocation.getCurrentPosition(updateLocation, error => { const reason = error.code === 1 ? '定位权限被拒绝' : '暂时无法获取位置'; alert(`${reason}。请检查浏览器地址栏旁的位置权限，或手动填写位置。`); }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 }); }
  document.querySelector('#allowLocation').onclick = requestLocation; document.querySelector('#manualLocation').onclick = () => { locationDialog.close(); locationInput.focus(); locationInput.select(); }; locationDialog.showModal(); requestLocation();
  const views = { '5 km': { radius: 5000, zoom: 14 }, '10 km': { radius: 10000, zoom: 13 }, '全武汉': { radius: 30000, zoom: 11 } };
  document.querySelectorAll('.segments button').forEach(button => button.addEventListener('click', () => { const next = views[button.textContent.trim()]; rangeCircle.setRadius(next.radius); leafletMap.flyTo(userMarker.getLatLng(), next.zoom, { animate: true, duration: .7 }); }));
  const companyPoints = [{ id: 1, name: '极光互动科技', days: 12, point: [30.513,114.411] },{ id: 2, name: '知途教育咨询', days: 46, point: [30.526,114.419] },{ id: 3, name: '禾风智能制造', days: 8, point: [30.497,114.433] },{ id: 4, name: '星桥新零售', days: 27, point: [30.507,114.383] },{ id: 5, name: '云迹数据服务', days: 19, point: [30.534,114.396] },{ id: 6, name: '安途人力资源', days: 63, point: [30.486,114.374] }];
  companyPoints.forEach(company => L.marker(company.point, { icon: L.divIcon({ className: 'company-pin-wrap', html: '<span class="company-pin">▣</span>', iconSize: [32,32], iconAnchor: [16,16] }) }).addTo(leafletMap).bindTooltip(`${company.name} · 招聘 ${company.days} 天`).on('click', () => window.openCompany && window.openCompany(company.id)));
  const annotateCards = () => document.querySelectorAll('.company').forEach(card => { if (card.querySelector('.posted-days')) return; const item = companyPoints.find(c => c.id === +card.dataset.id); if (item) card.querySelector('.company-main p').insertAdjacentHTML('beforeend', `<span class="posted-days"> · 招聘 ${item.days} 天</span>`); });
  new MutationObserver(annotateCards).observe(document.querySelector('#companies'), { childList: true }); annotateCards();
  const refreshMapSize = () => leafletMap.invalidateSize({ animate: false });
  window.addEventListener('resize', refreshMapSize); window.addEventListener('orientationchange', () => setTimeout(refreshMapSize, 250)); document.addEventListener('visibilitychange', () => { if (!document.hidden) setTimeout(refreshMapSize, 100); }); if (window.ResizeObserver) new ResizeObserver(refreshMapSize).observe(mapElement); setTimeout(refreshMapSize, 300); setTimeout(refreshMapSize, 1200);
  document.querySelector('#listToggle').onclick = () => { const card = document.querySelector('.map-card'); card.classList.toggle('collapsed'); document.querySelector('#listToggle').textContent = card.classList.contains('collapsed') ? '显示地图 ⌖' : '列表视图 ☷'; if (!card.classList.contains('collapsed')) setTimeout(refreshMapSize, 20); };
})();
document.querySelector('#reportScore option[value=""]').value = '3';
