(() => {
  const mapElement=document.querySelector('#mapCanvas');
  const map=L.map(mapElement,{zoomControl:true,attributionControl:true}).setView(window.Hanpin.center(),11);window.hanpinMap=map;
  const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);tiles.on('tileerror',()=>{document.querySelector('#locationStatus').textContent='地图底图暂时加载失败；定位、搜索和公司列表仍可使用，请检查网络后重试。'});
  const user=L.circleMarker(window.Hanpin.center(),{radius:8,color:'#fff',weight:3,fillColor:'#3d7ef0',fillOpacity:1}).addTo(map).bindTooltip('当前城市中心');
  const circle=L.circle(window.Hanpin.center(),{radius:5000,color:'#6f9e12',weight:1,fillColor:'#b8e742',fillOpacity:.08}).addTo(map);
  let customMarker;
  let currentOrigin;
  function saveCustom(point,label){if(customMarker)customMarker.remove();currentOrigin=point;customMarker=L.marker(point,{draggable:true,autoPan:true,icon:L.divIcon({className:'company-pin-wrap',html:'<span class="company-pin official">⌖</span>',iconSize:[32,32],iconAnchor:[16,16]})}).addTo(map).bindTooltip(label||'自定义位置').openTooltip().on('dragend',event=>reverse([event.target.getLatLng().lat,event.target.getLatLng().lng]));localStorage.setItem('hanpin-custom-location',JSON.stringify({point,label}));document.querySelector('#addressInput').value=label||`${point[0].toFixed(6)}, ${point[1].toFixed(6)}`;document.querySelector('#locationStatus').textContent=`已保存精确位置：${document.querySelector('#addressInput').value}（可拖动图钉微调）`;applyDistances();window.dispatchEvent(new CustomEvent('hanpin:customlocation',{detail:{point,label}}));}
  async function reverse(point){try{const result=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${point[0]}&lon=${point[1]}&zoom=18`,{headers:{Accept:'application/json'}}).then(r=>r.json());saveCustom(point,result.display_name||`${point[0].toFixed(6)}, ${point[1].toFixed(6)}`)}catch{saveCustom(point,`${point[0].toFixed(6)}, ${point[1].toFixed(6)}`)}}
  map.on('click',event=>reverse([event.latlng.lat,event.latlng.lng]));
  document.querySelector('#addressLocate').onclick=async()=>{const query=document.querySelector('#addressInput').value.trim();if(!query)return document.querySelector('#addressInput').focus();document.querySelector('#locationStatus').textContent='正在查找地址…';try{const list=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=cn&q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}}).then(r=>r.json());if(!list.length)throw new Error();const point=[Number(list[0].lat),Number(list[0].lon)];map.flyTo(point,16,{animate:true});saveCustom(point,list[0].display_name)}catch{document.querySelector('#locationStatus').textContent='没有找到该地址。请补充城市、区县、街道，或直接点击地图选点。'}};
  document.querySelector('#clearLocation').onclick=()=>{if(customMarker){customMarker.remove();customMarker=null}currentOrigin=null;localStorage.removeItem('hanpin-custom-location');document.querySelector('#addressInput').value='';document.querySelector('#locationStatus').textContent='已清除自定义位置。可输入地址、点击地图或使用浏览器定位。'};
  try{const saved=JSON.parse(localStorage.getItem('hanpin-custom-location')||'null');if(saved?.point)saveCustom(saved.point,saved.label)}catch{}
  let listingMarkers=[];
  function km(a,b){const r=Math.PI/180,dLat=(b[0]-a[0])*r,dLng=(b[1]-a[1])*r,x=Math.sin(dLat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dLng/2)**2;return 12742*Math.asin(Math.sqrt(x))}function applyDistances(){if(!currentOrigin)return;listingMarkers.forEach(({marker,entry,point})=>{const value=km(currentOrigin,point),card=document.querySelector(`[data-public="${CSS.escape(entry.id)}"] .company-name span`);if(card)card.textContent=`约 ${value<10?value.toFixed(1):Math.round(value)} km`})}function placeMarkers(detail){listingMarkers.forEach(x=>x.marker.remove());listingMarkers=[];const [lat,lng]=detail.center;detail.entries.forEach((entry,index)=>{const point=entry.point||[lat+Math.cos(index*2.39996)*(.018+index*.003),lng+Math.sin(index*2.39996)*(.018+index*.003)*1.25],marker=L.marker(point,{icon:L.divIcon({className:'company-pin-wrap',html:`<span class="company-pin ${entry.kind==='community'?'closed':'official'}">▣</span>`,iconSize:[32,32],iconAnchor:[16,16]})}).addTo(map).bindTooltip(`${entry.name} · ${entry.jobs}`,{direction:'top'}).on('click',()=>window.Hanpin.openListing?.(entry.id));listingMarkers.push({marker,entry,point})});applyDistances()}
  const cityCenters=new Map;let cityRequest=0;
  async function locateCity(detail){const key=`${detail.province}${detail.city}`,request=++cityRequest;let point=cityCenters.get(key);if(!point){try{const result=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=cn&q=${encodeURIComponent(key)}`,{headers:{Accept:'application/json'}}).then(r=>r.json());if(result.length){point=[Number(result[0].lat),Number(result[0].lon)];cityCenters.set(key,point)}}catch(error){console.warn('城市坐标解析失败',key,error)}}if(request!==cityRequest)return;point=point||detail.center;user.setLatLng(point).bindTooltip(`${detail.city}中心`);circle.setLatLng(point);map.flyTo(point,detail.radius==='全市'?10:12,{animate:true,duration:.7});placeMarkers({...detail,center:point});}
  window.addEventListener('hanpin:regionchange',e=>locateCity(e.detail));
  window.addEventListener('hanpin:listingschange',e=>placeMarkers(e.detail));
  window.addEventListener('hanpin:geolocate',e=>{const p=[e.detail.latitude,e.detail.longitude];user.setLatLng(p).bindTooltip('浏览器定位');circle.setLatLng(p);map.flyTo(p,13,{animate:true,duration:.7});});
  document.querySelectorAll('.segments button').forEach(button=>button.addEventListener('click',()=>circle.setRadius(button.textContent.trim()==='10 km'?10000:button.textContent.trim()==='全市'?50000:5000)));
  const refresh=()=>map.invalidateSize({animate:false});window.addEventListener('resize',refresh);window.addEventListener('load',()=>{refresh();setTimeout(refresh,250);setTimeout(refresh,900)});window.addEventListener('orientationchange',()=>setTimeout(refresh,350));if(window.ResizeObserver)new ResizeObserver(refresh).observe(mapElement);document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(refresh,100)});setTimeout(refresh,300);
})();
